const $ = id => document.getElementById(id);
const names = {alex:'Alex',maya:'Maya',customer:'You'};
let stage=0, epoch=0, started=false, recognition, listening=false;
const synth=window.speechSynthesis;
// Browser voice ordering is not a quality ranking. Prefer natural English voices.
function selectVoice(who) {
  const voices = synth.getVoices().filter(v => /^en(?:-|_)/i.test(v.lang));
  const preferred = who === 'maya'
    ? ['Samantha', 'Ava', 'Karen', 'Google US English', 'Microsoft Aria', 'Daniel']
    : ['Daniel', 'Alex', 'Google UK English Male', 'Microsoft Guy', 'Samantha'];
  for (const name of preferred) {
    const matches = voices.filter(v => v.name.toLowerCase().includes(name.toLowerCase()));
    if (matches.length) return matches.find(v => /premium|enhanced|natural/i.test(v.name)) || matches[0];
  }
  return voices.find(v => v.default) || voices.find(v => v.lang === 'en-US') || voices[0] || null;
}

function entry(who,text,meta='') {const row=document.createElement('div');row.className='turn';const avatar=document.createElement('div');avatar.className=`avatar ${who==='customer'?'human':who}`;avatar.textContent=names[who][0];const body=document.createElement('div');const name=document.createElement('strong');name.textContent=names[who];const detail=document.createElement('small');detail.textContent=meta;const p=document.createElement('p');p.textContent=text;body.append(name,detail,p);row.append(avatar,body);$('transcript').append(row);$('transcript').scrollTop=$('transcript').scrollHeight;}
function event(text){const el=document.createElement('div');el.className='event';el.textContent=text;$('transcript').append(el);}
function clearSpeaking(){for(const who of Object.keys(names)){$(who).classList.remove('speaking');$(who).querySelector('.state').textContent=who==='maya'&&stage<2?'On standby':'Listening';}}
function stop(){epoch++;synth?.cancel();clearSpeaking();$('status').textContent='Interrupted. Tell either agent what changed.';}
function update(step,evidence,next){[...$('steps').children].forEach((el,i)=>{el.className=i<step?'done':i===step?'active':''});if(evidence)$('evidence').textContent=evidence;$('next').textContent=next;}
async function say(who,text,token){if(token!==epoch)return;entry(who,text,who==='alex'?'Customer care':'Technical specialist');clearSpeaking();$(who).classList.add('speaking');$(who).querySelector('.state').textContent='Speaking';$('status').textContent=`${names[who]} is speaking. You can interrupt at any time.`;await new Promise(resolve=>{if(!$('audio').checked||!synth){setTimeout(resolve,700);return;}const utterance=new SpeechSynthesisUtterance(text);utterance.voice=selectVoice(who);utterance.rate=1;utterance.pitch=1;utterance.onend=resolve;utterance.onerror=resolve;synth.speak(utterance);});if(token===epoch){clearSpeaking();$('status').textContent='Your turn. Speak or type a reply.';}}
async function begin(){stop();started=true;stage=1;$('start').disabled=true;update(0,'No checks yet. Diagnostics are simulated.','Describe your connection problem.');await say('alex','Hi, I’m Alex from customer care. Maya, our technical specialist, is available in this room. What’s happening with your connection?',epoch);}
async function respond(text){if(!text.trim())return;if(listening)recognition?.stop();stop();const token=epoch;entry('customer',text);if(!started){started=true;$('start').disabled=true;stage=1;}const t=text.toLowerCase();
if(/human|technician|escalate/.test(t)){stage=5;update(4,'Demo escalation prepared. No real ticket or appointment created.','Review the case summary with customer care.');await say('maya','Alex, please take over. We should arrange a human technician rather than repeat troubleshooting.',token);await say('alex','I can prepare an escalation with our conversation and completed checks. This demo does not create a real service ticket.',token);return;}
if(/working now|back online|green|fixed|connected now/.test(t)&&stage>=2){stage=5;update(4,'Customer reports connection restored. No live measurement performed.','Try opening a website to verify recovery.');await say('maya','That sounds promising. Please open a website to confirm the connection is usable.',token);await say('alex','I have the troubleshooting summary here. Once you confirm that test, we can close the demo case.',token);return;}
if(stage<=1){stage=2;update(2,'Simulated service lookup: no area outage. Router state: awaiting customer observations.','Tell Maya which lights are on and their colours.');event('Alex → Maya · technical consultation requested');await say('alex','The simulated service check shows no area outage. Maya, could you help us check the router connection?',token);await say('maya','Of course. I’m Maya. Is the power light on, and what colour is the internet light? Please don’t unplug anything yet.',token);}
else if(stage===2){if(!/red|off|no light|power|amber|orange/.test(t)){await say('maya','Before choosing a check, I need the router observations. Is the power light on? Is the internet light red, amber, or off?',token);return;}stage=3;update(3,`Customer observation: ${text}. Simulated outage check: clear.`,'Check the cable between the router WAN port and modem or wall connection.');await say('maya','Thanks. Check whether the cable from the modem or wall connection is firmly seated in the router’s WAN or internet port. Tell me whether it was loose. Do not reset the router.',token);}
else if(stage===3){stage=4;update(4,`Customer observation: ${text}. Physical connection check discussed; recovery unverified.`,'Tell Maya whether internet access has returned.');await say('maya','Now check the internet light and try loading a website. Has access returned, or is the light still red?',token);}
else if(stage===4){stage=5;update(4,'Connection unresolved according to customer. Demo escalation prepared; no real ticket created.','Customer care can prepare the handoff summary.');event('Maya → Alex · unresolved connection; escalation recommended');await say('maya','Alex, the customer still reports no connection after the physical cable check. We need a human technician or further authenticated diagnostics.',token);await say('alex','I’ll carry the observations into the escalation so you won’t need to repeat them. In a production system I would check appointment availability. Here, this is a simulated handoff only.',token);}
else await say(/maya/.test(t)?'maya':'alex','This demo case is at its final checkpoint. Start a new session to test another path, or ask for a human escalation.',token);
}
$('form').onsubmit=e=>{e.preventDefault();const value=$('message').value;$('message').value='';respond(value);};$('start').onclick=begin;$('interrupt').onclick=stop;$('audio').onchange=()=>{if(!$('audio').checked)stop();};$('reset').onclick=()=>{stop();recognition?.abort();stage=0;started=false;$('transcript').replaceChildren();$('start').disabled=false;clearSpeaking();update(0,'No checks yet. All results in this prototype are simulated.','Tell Alex what’s happening.');$('status').textContent='Start the demo, then describe your connection problem.';};
const SR=window.SpeechRecognition||window.webkitSpeechRecognition;
if(SR){recognition=new SR();recognition.lang='en-US';recognition.interimResults=false;recognition.onstart=()=>{listening=true;$('mic').textContent='Stop listening';$('customer').classList.add('speaking');$('status').textContent='Listening. Browser speech recognition may use an external service.';};recognition.onend=()=>{listening=false;$('mic').textContent='🎙 Speak';$('customer').classList.remove('speaking');};recognition.onresult=e=>respond(e.results[0][0].transcript);recognition.onerror=e=>{$('status').textContent=`Microphone: ${e.error}. You can type your reply.`;};$('mic').onclick=()=>{if(listening){recognition.stop();return;}stop();try{recognition.start();}catch{$('status').textContent='Microphone is busy. Please type or try again.';}};}else{$('mic').disabled=true;$('voice-note').textContent='Speech recognition unavailable · use typed input';}
